// notes.js — the co-pilot's field notes: capture, dedupe, decay, retrieval,
// and the behavioral-telemetry harvest. This is the memory layer of the
// Mentalist Engine: atomic timestamped observations with importance and
// provenance, consolidated later (Phase 2) by the sleep cycle.

import { notes as noteStore, crumbs, rhythm, harvestMark, sleepMeter, urges } from './store.js';

const MAX_ACTIVE = 1500;
const KINDS = ['pattern', 'trigger', 'state', 'win', 'value', 'fact'];

// The markers the model is instructed to use, plus variants stripped defensively.
export const OBS_OPEN = '⟪obs⟫';
export const OBS_CLOSE = '⟪/obs⟫';
const OPEN_VARIANTS = [OBS_OPEN, '<obs>', '<observations>'];
const CLOSE_VARIANTS = [OBS_CLOSE, '</obs>', '</observations>'];

// ---------- text utils ----------
const STOP = new Set(['the', 'a', 'an', 'and', 'or', 'but', 'of', 'to', 'in', 'on', 'at', 'for', 'with', 'is', 'was', 'are', 'be', 'been', 'it', 'its', 'my', 'me', 'that', 'this', 'they', 'them', 'their', 'you', 'your', 'has', 'had', 'have', 'not', 'about', 'when', 'what', 'how', 'again', 'just', 'like', 'get', 'got']);

export function tokens(s) {
  return (s || '')
    .toLowerCase()
    .replace(/[“”"'’‘]/g, '')
    .split(/[^a-z0-9]+/)
    .filter(w => w.length > 2 && !STOP.has(w));
}

// ---------- observation block parsing ----------
// Strip the obs block from text for DISPLAY, including a partially-streamed
// marker at the tail (so the marker never flashes on screen mid-stream).
export function stripObs(text) {
  let cut = text.length;
  for (const p of OPEN_VARIANTS) {
    const i = text.indexOf(p);
    if (i !== -1 && i < cut) cut = i;
  }
  let out = text.slice(0, cut);
  // hold back any suffix that could be the start of a marker still streaming in
  for (const p of OPEN_VARIANTS) {
    for (let k = Math.min(p.length - 1, out.length); k > 0; k--) {
      if (out.endsWith(p.slice(0, k))) { out = out.slice(0, out.length - k); break; }
    }
  }
  return out.replace(/\s+$/, '');
}

// Split a completed reply into the visible text and the parsed observations.
export function parseObs(text) {
  let at = -1, open = '';
  for (const p of OPEN_VARIANTS) {
    const i = text.indexOf(p);
    if (i !== -1 && (at === -1 || i < at)) { at = i; open = p; }
  }
  if (at === -1) return { clean: text.trim(), obs: [] };
  const clean = text.slice(0, at).replace(/\s+$/, '');
  let raw = text.slice(at + open.length);
  for (const c of CLOSE_VARIANTS) {
    const j = raw.indexOf(c);
    if (j !== -1) { raw = raw.slice(0, j); break; }
  }
  let arr = [];
  try { arr = JSON.parse(raw.trim()); } catch { /* malformed block — drop it, keep the reply */ }
  if (!Array.isArray(arr)) arr = [];
  return { clean, obs: arr.map(sanitize).filter(Boolean).slice(0, 2) };
}

// Validate and normalize a model-emitted observation. The model may only
// claim 'stated' or 'inferred' provenance — 'behavioral' is reserved for
// telemetry generated by app code, and nothing is ever 'assistant'-sourced.
function sanitize(o) {
  if (!o || typeof o.text !== 'string' || !o.text.trim()) return null;
  const text = o.text.trim().slice(0, 240);
  const kw = (Array.isArray(o.keywords) ? o.keywords : [])
    .map(k => String(k).toLowerCase().trim())
    .filter(k => k && k.length <= 24)
    .slice(0, 5);
  return {
    text,
    kind: KINDS.includes(o.kind) ? o.kind : 'fact',
    prov: o.provenance === 'stated' ? 'stated' : 'inferred',
    imp: Math.min(10, Math.max(1, Math.round(Number(o.importance) || 3))),
    kw: kw.length ? kw : tokens(text).slice(0, 5),
  };
}

// ---------- recording, dedupe, decay, cap ----------
export function decayScore(n) {
  const hours = (Date.now() - n.la) / 36e5;
  return Math.pow(0.995, hours) * (n.imp / 10);
}

// Record one observation. A near-duplicate reinforces the existing note
// (evidence count + freshness) instead of piling up copies.
export function record(o) {
  const norm = o.text.toLowerCase().replace(/\s+/g, ' ');
  const dupe = noteStore.active().find((n) => {
    if (n.kind !== o.kind) return false;
    if (n.text.toLowerCase().replace(/\s+/g, ' ') === norm) return true;
    const theirs = new Set(n.kw);
    const inter = o.kw.filter(k => theirs.has(k)).length;
    return inter >= 3;
  });
  if (dupe) {
    noteStore.update(dupe.id, {
      ev: dupe.ev + 1,
      la: Date.now(),
      imp: Math.max(dupe.imp, o.imp),
      // an observation the user states outright upgrades an inferred one
      prov: o.prov === 'stated' ? 'stated' : dupe.prov,
    });
    sleepMeter.bumpImp(o.imp); // reinforcement counts toward the next sleep cycle
    return { id: dupe.id, reinforced: true };
  }
  const note = {
    id: Date.now() + Math.random().toString(16).slice(2),
    ts: Date.now(),
    la: Date.now(),
    text: o.text,
    kind: o.kind,
    imp: o.imp,
    prov: o.prov,
    ev: 1,
    status: 'active',
    kw: o.kw,
  };
  noteStore.add(note);
  sleepMeter.bumpImp(o.imp);
  enforceCap();
  return { id: note.id, reinforced: false };
}

// Undo the results of the most recent capture: new notes are deleted,
// reinforcements are rolled back.
export function unrecord(results) {
  results.forEach((r) => {
    const n = noteStore.get(r.id);
    if (!n) return;
    if (r.reinforced) noteStore.update(r.id, { ev: Math.max(1, n.ev - 1) });
    else noteStore.remove(r.id);
  });
}

function enforceCap() {
  const act = noteStore.active();
  if (act.length <= MAX_ACTIVE) return;
  [...act]
    .sort((a, b) => decayScore(a) - decayScore(b))
    .slice(0, act.length - MAX_ACTIVE)
    .forEach(n => noteStore.update(n.id, { status: 'tombstone' }));
}

// ---------- retrieval (no embeddings: idf-weighted overlap + importance + recency) ----------
export function relevant(msg, n = 5) {
  const q = new Set(tokens(msg));
  if (!q.size) return [];
  const act = noteStore.active();
  const df = {};
  const wordSets = act.map((note) => {
    const words = new Set([...note.kw, ...tokens(note.text)]);
    words.forEach(w => { df[w] = (df[w] || 0) + 1; });
    return words;
  });
  const scored = [];
  act.forEach((note, i) => {
    let overlap = 0;
    q.forEach(w => { if (wordSets[i].has(w)) overlap += 1 / Math.log2(2 + (df[w] || 1)); });
    if (!overlap) return;
    scored.push({
      note,
      score: overlap + 0.7 * (note.imp / 10) + 0.5 * Math.pow(0.995, (Date.now() - note.la) / 36e5),
    });
  });
  scored.sort((a, b) => b.score - a.score);
  const top = scored.slice(0, n).map(s => s.note);
  top.forEach(note => noteStore.update(note.id, { la: Date.now() }));  // recall refreshes memory
  return top;
}

// ---------- behavioral telemetry harvest ----------
// Converts breadcrumbs the app already logs into rhythm counts and
// 'behavioral' field notes. Runs cheaply on co-pilot entry; crumbs are
// capped at 30 so the watermark keeps us from double-counting.
const CRUMB_RULES = [
  { re: /hit “I'?m Spiraling”/i, spiral: true },
  { re: /rode out an urge wave \((\d+|\?)→(\d+|\?)\)/i, note: m => ({ text: `Rode out an urge wave (intensity ${m[1]}→${m[2]})`, kind: 'win', imp: 6, kw: ['urge', 'wave', 'ridden'] }) },
  { re: /took an urge wave to the co-pilot/i, note: () => ({ text: 'An urge wave was big enough to need talking through', kind: 'state', imp: 5, kw: ['urge', 'wave', 'support'] }) },
  { re: /trying to: “(.+)”/i, note: m => ({ text: `A spiral interrupted: ${m[1]}`, kind: 'trigger', imp: 5, kw: [...tokens(m[1]).slice(0, 4), 'spiral'] }) },
  { re: /FINISHED: “(.+)” — every step done/i, note: m => ({ text: `Finished “${m[1]}” by micro-stepping`, kind: 'win', imp: 5, kw: [...tokens(m[1]).slice(0, 4), 'finished'] }) },
  { re: /started micro-stepping: “(.+)”/i, note: m => ({ text: `Couldn't start “${m[1]}” — used the stepper`, kind: 'trigger', imp: 4, kw: [...tokens(m[1]).slice(0, 4), 'stuck'] }) },
  { re: /brain-dumped (\d+) thing/i, note: m => ({ text: `Brain-dumped ${m[1]} items to clear their head`, kind: 'state', imp: 3, kw: ['brain', 'dump', 'overload'] }) },
  { re: /hit “I Forgot”/i, note: () => ({ text: 'Lost their thread mid-task (used the Retracer)', kind: 'state', imp: 3, kw: ['forgot', 'blank', 'memory'] }) },
];

export function harvestTelemetry() {
  const since = harvestMark.get();
  const fresh = crumbs.recent(30).filter(c => c.ts > since);
  if (!fresh.length) return 0;
  let made = 0;
  // oldest first so rhythm/notes build in event order
  [...fresh].reverse().forEach((c) => {
    const hour = new Date(c.ts).getHours();
    let spiral = false;
    for (const rule of CRUMB_RULES) {
      const m = c.text.match(rule.re);
      if (!m) continue;
      if (rule.spiral) spiral = true;
      if (rule.note) {
        record({ ...rule.note(m), prov: 'behavioral' });
        made++;
      }
      break;
    }
    rhythm.bump(hour, spiral);
  });
  harvestMark.set(fresh[0].ts); // crumbs.recent() is newest-first
  return made;
}

// ---------- summaries for the system prompt & The File ----------
export function urgeSummary() {
  const u = urges.get();
  if (!u.log.length) return null;
  const week = u.log.filter(e => Date.now() - e.ts < 7 * 864e5).length;
  const counts = {};
  u.log.forEach((e) => { if (e.trigger) counts[e.trigger] = (counts[e.trigger] || 0) + 1; });
  const top = Object.entries(counts).sort((a, b) => b[1] - a[1])[0];
  const total = u.hourly.reduce((a, b) => a + b, 0);
  let peak = '';
  if (total >= 3) {
    const h = u.hourly.indexOf(Math.max(...u.hourly));
    peak = `, peak hour ~${String(h).padStart(2, '0')}:00`;
  }
  return `${u.ridden} wave${u.ridden === 1 ? '' : 's'} ridden of ${u.log.length} logged (${week} this week)` +
    `${top ? `, usual trigger: ${top[0]}` : ''}${peak}`;
}

export function rhythmSummary() {
  const r = rhythm.get();
  const total = r.hourly.reduce((a, b) => a + b, 0);
  if (total < 8) return null;
  const label = (h) => `${String(h).padStart(2, '0')}:00`;
  const peaks = r.hourly
    .map((v, h) => ({ v, h }))
    .sort((a, b) => b.v - a.v)
    .slice(0, 2)
    .filter(x => x.v > 0)
    .map(x => label(x.h));
  const spiralTotal = r.spirals.reduce((a, b) => a + b, 0);
  const spiralPeaks = r.spirals
    .map((v, h) => ({ v, h }))
    .sort((a, b) => b.v - a.v)
    .slice(0, 2)
    .filter(x => x.v > 0)
    .map(x => label(x.h));
  let s = `Most active around ${peaks.join(' and ')}.`;
  if (spiralTotal > 0) s += ` ${spiralTotal} spiral${spiralTotal > 1 ? 's' : ''} logged${spiralPeaks.length ? ', clustering near ' + spiralPeaks.join(' and ') : ''}.`;
  return s;
}
